name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ConvertMarkdownToDocx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: prep output
        run: mkdir imagesOutput
      - uses: docker://pandoc/core:2.9
        with:
          args: 00-Outline.md 01-Chapter1.md 02-Chapter2.md --to=docx --output=book.docx --toc --standalone # --extract-media=. # --standalone # --extract-media=imagesOutput #--from=gfm --standalone 
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: book.docx
